FROM mcr.microsoft.com/dotnet/sdk:9.0
WORKDIR /app

# Copy csproj and restore as distinct layers to leverage caching
COPY *.csproj ./
RUN dotnet restore

# Copy the rest of the application source code
COPY . ./

# Expose the port your app will run on
EXPOSE 8080

# Run the app with dotnet watch for hot-reloading
ENTRYPOINT ["dotnet", "watch", "run", "--urls", "http://*:8080"]